name: eslint-check

on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install eslint
      - run: npm install eslint-config-airbnb-base
      - run: npm install eslint-plugin-import
      - run: make lint